version: '3'

services:

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    command: bash -c "rabbitmq-server & rabbitmq-plugins enable rabbitmq_management && sleep 5 && rabbitmqadmin declare queue name=task_queue durable=true && rabbitmqadmin declare queue name=message_queue durable=true && tail -f /dev/null"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.9

  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    volumes:
      - ./consul-data:/consul/data
      - ./consul-config:/consul/config
    networks:
      magellon-network:
        ipv4_address: 172.16.238.10


  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./grafana/config.monitoring
    networks:
      magellon-network:
        ipv4_address: 172.16.238.12

  backend:
    image: khoshbin/magellon-main-service
    container_name: magellon-main-service
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - /mnt/hpc:/app/data
    environment:
      - CONSUL_HOST=consul
      - RABBITMQ_HOST=rabbitmq
    networks:
      magellon-network:
        ipv4_address: 172.16.238.15

#  backend1:
#    image: khoshbin/magellon-main-service
#    restart: unless-stopped
#    ports:
#      - "8001:8000"
#    volumes:
#      - /mnt/hpc:/app/data
#    environment:
#      - CONSUL_HOST=consul
#      - CONSUL_PORT=8500
#
#
#  backend2:
#    image: khoshbin/magellon-main-service
#    restart: unless-stopped
#    ports:
#      - "8002:8000"
#    volumes:
#      - /mnt/hpc:/app/data
#    environment:
#      - CONSUL_HOST=consul
#      - CONSUL_PORT=8500


#  web:
#    build: .
#    ports:
#      - "3000:5000"
#    depends_on:
#      - backend
  #  prometheus:
  #    image: prom/prometheus:latest
  #    ports:
  #      - "9090:9090"
  #    volumes:
  #        - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  web:
    image: khoshbin/magellon-angular-app
    container_name: magellon-angular-app
    restart: unless-stopped
    ports:
      - "8282:80"
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - CONSUL_HOST=consul
    networks:
      magellon-network:
        ipv4_address: 172.16.238.16



networks:
  magellon-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
#  web2:
#    build: ./web
#    ports:
#     - "5000:5000"
#    links
#     - db
#  db:
#    build: ./db