---
- name: Build, push, and run Docker container
  hosts: target
  gather_facts: false
  become: true

  vars:
    project_path: /projects/CoreService
    project_directory: /projects/CoreService
    git_repository: https://github.com/sstagg/Magellon.git
    dockerfile_path: /projects/infrastructure/docker/Dockerfile
    api_url: http://maia.cryoem.fsu.edu:8080/web/
    image_name: khoshbin/magellon-core-service
    container_name: magellon-core-service01

  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: magellon
        
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ project_directory }}"
          dockerfile: "{{ dockerfile_path }}"
          pull: no
          nocache: yes
        source: build


    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        network_mode: magellon
        ports:
          - "8181:80"

