- name: Install and Configure MySQL Server
  hosts: target
  gather_facts: false
  remote_user: root
  vars:
    mysql_new_root_password: behd1d2
    mysql_database: magellon01

    mysql_magellon_user: magellon
    mysql_magellon_password: magell0n#0367
    sql_source_file_path: ../assets/sql/magellon01db.sql
    sql_target_file_path: /projects/sql/magellon01db.sql
  tasks:


    - name: Scan host key
      command: ssh-keyscan -H 5.161.91.240
      register: host_key

    - name: Add host key to known_hosts
      lineinfile:
        dest: /home/behdad/.ssh/known_hosts
        line: "{{ host_key.stdout }}"
        create: yes
        mode: "0600"

    - name: Run apt update
      become: true
      apt:
        update_cache: yes

    - name: Install Python3 and pip and pymysql
      apt:
        name:
          - python3
          - python3-pip
          - python3-pymysql
          - graphviz
        state: present


    - name: Install MariaDB Server
      apt:
        name:
          - mariadb-server
          - mariadb-client
          - python3-pip
          - curl
        state: present

    - name: Set lower table names in MariaDB configuration
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^lower_case_table_names'
        line: 'lower_case_table_names = 1'
        state: present
      become: true

    - name: Set MariaDB to listen on 0.0.0.0
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
      become: true

    - name: Restart MariaDB service
      service:
        name: mariadb
        state: restarted
      become: true

    - name: Enable MySQL service on boot
      systemd:
        name: mysql
        enabled: yes

    - name: Change MariaDB root password
      mysql_user:
        name: root
        password: "{{ mysql_new_root_password }}"
        update_password: always
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: true
      ignore_errors: yes


    - name: Create Magellon User
      mysql_user:
        name: "{{ mysql_magellon_user }}"
        host: '%'
        password: "{{ mysql_magellon_password }}"
        priv: '*.*:ALL'
        state: present
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
      become: true

    - name: Create MariaDB database
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: "root"
        login_password: "{{ mysql_new_root_password }}"
      become: true

    - name: Make sure destination dir exists
      file:
        path: "{{ sql_target_file_path | dirname }}"
        recurse: true
        state: directory

    - name: Copy File to Remote Server
      copy:
        src: "{{ sql_source_file_path }}"
        dest: "{{ sql_target_file_path }}"

    - name: Import SQL file
      mysql_db:
        name: "{{ mysql_database }}"
        state: import
        target: "{{ sql_target_file_path }}"
        login_user: "{{ mysql_magellon_user }}"
        login_password: "{{ mysql_magellon_password }}"