services:
#  postgres:
#    image: postgis/postgis:latest
#    container_name: magellon-postgres_container
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      POSTGRES_DB: ${MYSQL_DATABASE}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - postgres_conf:/etc/postgresql
#    ports:
#      - "5432:5432"
#    networks:
#      magellon-network:
#        ipv4_address: 172.16.238.6

  mysql:
    image: mysql:8.2.0
    container_name: magellon-mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_conf:/etc/mysql/conf
      - mysql_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --lower-case-table-names=1
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.7


  rabbitmq:
    image: rabbitmq:management-alpine
#    image: rabbitmq:latest
#    image: rabbitmq:3-management
    hostname: my-rabbit
    restart: unless-stopped
    container_name: magellon-rabbitmq-container
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      magellon-network:
        ipv4_address: 172.16.238.8

  consul:
    image: consul:1.15.4
    restart: unless-stopped
    container_name: magellon-consul-container
    ports:
      - "${CONSUL_PORT}:8500"
    volumes:
      - consul_data:/consul/data
      - consul_config:/consul/config
    networks:
      magellon-network:
        ipv4_address: 172.16.238.9


  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: magellon-prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - prometheus_config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: magellon-grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - grafana_temp:/tmp
    command: |
      sh -c "cp /tmp/grafana.db /var/lib/grafana/grafana.db && /run.sh"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER_NAME}      # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_USER_PASS}    # Default admin password
    networks:
      magellon-network:
        ipv4_address: 172.16.238.12

  backend:
    build:
      context: ../CoreService
      dockerfile: Dockerfile
    image: magellon-core-image
    container_name: magellon-core-container
    restart: unless-stopped
    ports:
      - "${MAGELLON_BACKEND_PORT}:80"
    volumes:
      - magellon_home:/magellon
      - magellon_gpfs:/gpfs
    environment:
      - APP_ENV=production
      - RUN_ENV =docker
      - GPFS_PATH=${MAGELLON_GPFS_PATH}
      - HOME_PATH=${MAGELLON_HOME_PATH}
      - CONSUL_HOST=consul
      - RABBITMQ_HOST=rabbitmq
    networks:
      magellon-network:
        ipv4_address: 172.16.238.15
        
  web:
    build:
      context: ../magellon-react-app
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:${MAGELLON_BACKEND_PORT}
    image: magellon-react-app-image
    container_name: magellon-react-app-container
    restart: unless-stopped
    ports:
      - "${MAGELLON_FRONTEND_PORT}:80"
    environment:
      - BACKEND_HOST=backend
      - CONSUL_HOST=consul
      - API_URL=http://localhost:${MAGELLON_BACKEND_PORT}
    networks:
      magellon-network:
        ipv4_address: 172.16.238.16


  magellon_result_plugin:
    build:
      context: ../plugins/magellon_result_processor
      dockerfile: Dockerfile
    image: magellon_result_plugin_image
    container_name: magellon_result_container
    environment:
      - APP_ENV=production
      - RUN_ENV =docker
      - GPFS_ROOT=${MAGELLON_GPFS_PATH}
      - HOME_PATH=${MAGELLON_HOME_PATH}
    volumes:
      - magellon_gpfs:/gpfs
      - magellon_jobs:/jobs
      - magellon_home:/magellon
    ports:
      - "${MAGELLON_RESULT_PLUGIN_PORT}:80"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.20        
        
  magellon_ctf_plugin:
    build:
      context: ../plugins/magellon_ctf_plugin
      dockerfile: Dockerfile
    image: magellon_ctf_plugin_image
    container_name: magellon_ctf_plugin_container
    environment:
      - APP_ENV=production
      - RUN_ENV =docker
      - GPFS_ROOT=${MAGELLON_GPFS_PATH}
      - JOBS_PATH=${MAGELLON_JOBS_PATH}
    volumes:
      - magellon_gpfs:/gpfs
      - magellon_jobs:/jobs
    ports:
      - "${MAGELLON_CTF_PLUGIN_PORT}:80"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.21
  
  magellon_motioncor_plugin:
    build:
      context: ../plugins/magellon_motioncor_plugin
      dockerfile: Dockerfile
    image: magellon_motioncor_plugin_image
    container_name: magellon_motioncor_plugin_container
    environment:
      - APP_ENV=production
      - RUN_ENV =docker
      - GPFS_ROOT=${MAGELLON_GPFS_PATH}
      - JOBS_PATH=${MAGELLON_JOBS_PATH}
    volumes:
      - magellon_gpfs:/gpfs
      - magellon_jobs:/jobs
    ports:
      - "${MAGELLON_MOTIONCOR_PLUGIN_PORT}:80"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.22
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  # New named volumes for all services
  mysql_data: {}
  mysql_conf: {}
  mysql_init: {}
  rabbitmq_data: {}
  consul_data: {}
  consul_config: {}
  prometheus_config: {}
  grafana_storage: {}
  grafana_temp: {}
  magellon_home: {}
  magellon_gpfs: {}
  magellon_jobs: {}
  # Legacy volumes
  postgres_data: {}
  postgres_conf: {}
  rabbitmq-data: {}
  app_data: {}
  cache:
    driver: local

networks:
  magellon-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
