version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: behd1d2
      POSTGRES_DB: magellon01
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/conf:/etc/postgresql/postgresql.conf:rw
    ports:
      - "5432:5432"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.6

  mysql:
    image: mysql:8.4.2
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/conf:/etc/mysql/conf
      - ./mysql/init/magellon02db.sql:/docker-entrypoint-initdb.d/magellon02db.sql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --lower-case-table-names=1
    restart: always
    ports:
      - "3306:3306"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.7


  rabbitmq:
    image: rabbitmq:management-alpine
#    image: rabbitmq:latest
#    image: rabbitmq:3-management
    hostname: my-rabbit
    restart: unless-stopped
    container_name: rabbitmq-container
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # Persist data
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      magellon-network:
        ipv4_address: 172.16.238.8

  consul:
    image: consul:1.15.4
    restart: unless-stopped
    container_name: consul-container
    ports:
      - "8500:8500"
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config
    networks:
      magellon-network:
        ipv4_address: 172.16.238.9


  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      magellon-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./config.monitoring
    networks:
      magellon-network:
        ipv4_address: 172.16.238.12


  magellon_ctf_plugin:
    build:
      context: ../plugins/magellon_ctf_plugin
      dockerfile: Dockerfile
    image: magellon_ctf_plugin_image
    container_name: magellon_ctf_plugin_container
    environment:
      - APP_ENV=production
      - GPFS_ROOT=${MAGELLON_PATH}
      - JOBS_PATH=${MAGELLON_JOBS_PATH}
    volumes:
      - ${MAGELLON_PATH}:/gpfs
      - ${MAGELLON_JOBS_PATH}:/outputs
    ports:
      - "8010:80"

volumes:
  rabbitmq-data: { }
  postgres_data: { }
  app_data:  # Define a named volume for application data
  cache:
    driver: local

networks:
  magellon-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
