#!/usr/bin/env python
"""
MeasureIce-style ice thickness estimator (Beer-Lambert).

For each pixel:

    t(px) = -T_eff * ln(I(px) / I_0)

where I_0 is a vacuum-reference intensity and T_eff is the effective
mean-free-path. Both depend on microscope configuration; see README for
typical values.

Three I_0 strategies are supported:

  --i0-mode percentile   I_0 = np.percentile(image, --i0-percentile)
                         (default; works without prior knowledge)
  --i0-mode roi          I_0 = mean over (x,y,w,h) crop given by --i0-roi
  --i0-mode reference    I_0 = mean of a reference vacuum MRC given by
                         --i0-reference

Writes:
  <stem>_thickness.npy   (float32 H×W, in nm)
  <stem>_thickness.png   heatmap overlay
  <stem>_thickness.json  per-image summary stats
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Tuple

import numpy as np


# ---------------------------------------------------------------------------
# Two calibration paths:
#   1. HDF5 LUT generated by upstream MeasureIce's Generate_MeasureIce_calibration.py
#      (preferred — per-aperture, simulation-derived, ~0.5% agreement with
#      MeasureIce's published method across 0-600 nm).
#   2. Scalar T_eff fallback (Beer-Lambert with a single ALS coefficient).
#      Approximates a LUT to ~10% accuracy provided the right T_eff for the
#      microscope's aperture is chosen.
#
# At 300 kV the simulation-derived T_eff values are:
#   5 mrad   -> 396 nm
#   10 mrad  -> 588 nm
#   15 mrad  -> 799 nm   (typical 100 um Krios objective aperture)
#   20 mrad  -> 1049 nm
# ---------------------------------------------------------------------------
DEFAULT_T_EFF_NM = 395.0   # 300 kV, 5 mrad aperture (NOT 100 um — see table above)
T_EFF_PRESETS = {
    "200kV": 320.0,
    "300kV": 395.0,
}
DEFAULT_LUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "luts", "Krios_300kV.h5")
DEFAULT_APERTURE_MRAD = 15.0   # 100 um objective aperture at 300 kV


def load_lut(path: str, aperture_mrad: float):
    """Load a MeasureIce HDF5 LUT and build an inverse interpolator
    (I/I_0 -> thickness in nm) for the closest aperture column.

    Returns (interpolator, info_dict).
    """
    import h5py
    from scipy.interpolate import interp1d
    with h5py.File(path, "r") as f:
        thicknesses_nm = f["Thicknesses"][:]
        apertures_mrad = f["Apertures"][:]
        als = f["ALS coefficients"][:]
        log_i0 = f["LogI0/I"][:]      # shape (n_thickness, n_aperture)

    idx = int(np.argmin(np.abs(apertures_mrad - aperture_mrad)))
    chosen_mrad = float(apertures_mrad[idx])
    chosen_lambda_nm = float(als[idx])
    ratios = np.exp(-log_i0[:, idx])  # I/I_0 per thickness step, decreasing

    # interp1d wants increasing x -> reverse arrays
    interp = interp1d(
        ratios[::-1], thicknesses_nm[::-1],
        bounds_error=False,
        fill_value=(float(thicknesses_nm[-1]), 0.0),
        kind="linear",
    )
    info = {
        "lut_path": os.path.abspath(path),
        "lut_aperture_mrad": chosen_mrad,
        "lut_aperture_requested_mrad": aperture_mrad,
        "lut_lambda_nm": chosen_lambda_nm,
        "lut_thickness_range_nm": [float(thicknesses_nm[0]), float(thicknesses_nm[-1])],
    }
    return interp, info


def load_mrc(path: str) -> np.ndarray:
    import mrcfile  # lazy
    with mrcfile.open(path, permissive=True) as m:
        data = np.asarray(m.data, dtype=np.float32)
    if data.ndim == 3 and data.shape[0] == 1:
        data = data[0]
    if data.ndim != 2:
        raise ValueError(f"expected 2D MRC, got shape {data.shape} at {path}")
    return data


def resolve_t_eff(t_eff: float | None, preset: str | None) -> float:
    if t_eff is not None:
        return float(t_eff)
    if preset:
        if preset not in T_EFF_PRESETS:
            raise ValueError(f"unknown T_eff preset {preset!r}; "
                             f"options: {list(T_EFF_PRESETS)}")
        return T_EFF_PRESETS[preset]
    return DEFAULT_T_EFF_NM


def compute_i0(
    img: np.ndarray,
    mode: str,
    *,
    percentile: float = 99.0,
    roi: Tuple[int, int, int, int] | None = None,
    reference_path: str | None = None,
) -> Tuple[float, dict]:
    """Resolve the vacuum-reference intensity I_0.

    Returns ``(I_0, info)`` where ``info`` records how the value was
    obtained so the per-image JSON can flag low-confidence I_0s.
    """
    if mode == "percentile":
        i0 = float(np.percentile(img, percentile))
        return i0, {"i0_mode": "percentile", "i0_percentile": percentile}

    if mode == "roi":
        if roi is None:
            raise ValueError("--i0-mode roi requires --i0-roi x,y,w,h")
        x, y, w, h = roi
        crop = img[y:y + h, x:x + w]
        if crop.size == 0:
            raise ValueError(f"ROI {roi} is outside image of shape {img.shape}")
        i0 = float(crop.mean())
        return i0, {
            "i0_mode": "roi",
            "i0_roi": [x, y, w, h],
            "i0_roi_std": float(crop.std()),
        }

    if mode == "reference":
        if not reference_path:
            raise ValueError("--i0-mode reference requires --i0-reference PATH")
        ref = load_mrc(reference_path)
        i0 = float(ref.mean())
        return i0, {
            "i0_mode": "reference",
            "i0_reference": os.path.abspath(reference_path),
            "i0_reference_std": float(ref.std()),
        }

    raise ValueError(f"unknown --i0-mode {mode!r}")


def compute_thickness(
    img: np.ndarray,
    i0: float,
    *,
    t_eff_nm: float | None = None,
    lut_interp=None,
    clip_saturation_percentile: float = 99.99,
) -> Tuple[np.ndarray, dict]:
    """Pixel-wise thickness in nm.

    Pass either ``t_eff_nm`` (scalar Beer-Lambert) or ``lut_interp`` (a
    ratio->nm interpolator from :func:`load_lut`). Exactly one must be set.

    The saturation percentile is decoupled from the I_0 percentile; default
    99.99 only clips true detector hot pixels, never confounded with the
    vacuum reference.
    """
    if (t_eff_nm is None) == (lut_interp is None):
        raise ValueError("pass exactly one of t_eff_nm or lut_interp")

    sat_cap = float(np.percentile(img, clip_saturation_percentile))
    work = np.minimum(img, sat_cap)

    safe = np.where(work > 0, work, np.nan)
    ratio = safe / i0
    ratio_clipped = np.clip(ratio, 1e-6, 1.0)

    if lut_interp is not None:
        t = lut_interp(ratio_clipped.flatten()).reshape(ratio_clipped.shape)
        method = "lut"
    else:
        t = -t_eff_nm * np.log(ratio_clipped)
        method = "scalar"

    t = np.clip(t, 0.0, None)
    t = np.where(np.isfinite(t), t, 0.0).astype(np.float32)

    summary = {
        "method": method,
        "saturation_cap": sat_cap,
        "i0": float(i0),
        "mean_t_nm": float(np.nanmean(t)),
        "median_t_nm": float(np.nanmedian(t)),
        "p5_t_nm": float(np.nanpercentile(t, 5)),
        "p95_t_nm": float(np.nanpercentile(t, 95)),
        "thin_frac": float((t < 30).mean()),
        "thick_frac": float((t > 100).mean()),
    }
    if t_eff_nm is not None:
        summary["t_eff_nm"] = float(t_eff_nm)
    return t, summary


def save_outputs(
    path: str,
    img: np.ndarray,
    t: np.ndarray,
    summary: dict,
    *,
    output_dir: str | None = None,
    write_png: bool = True,
):
    stem = os.path.splitext(os.path.basename(path))[0]
    out_dir = output_dir or os.path.dirname(os.path.abspath(path))
    os.makedirs(out_dir, exist_ok=True)

    np.save(os.path.join(out_dir, f"{stem}_thickness.npy"), t)
    with open(os.path.join(out_dir, f"{stem}_thickness.json"), "w") as f:
        json.dump(summary, f, indent=2)

    if write_png:
        import matplotlib.pyplot as plt
        fig, axes = plt.subplots(1, 2, figsize=(14, 6))
        # left: raw image
        lo, hi = np.percentile(img, [1, 99])
        axes[0].imshow(img, cmap='gray', vmin=lo, vmax=hi)
        axes[0].set_title(f"{stem}\nintensity")
        axes[0].axis('off')
        # right: thickness heatmap
        finite = t[np.isfinite(t)]
        vmax = float(np.percentile(finite, 99)) if finite.size else 100.0
        im = axes[1].imshow(t, cmap='viridis', vmin=0.0, vmax=vmax)
        axes[1].set_title(f"thickness (nm)\nmean={summary['mean_t_nm']:.1f} "
                          f"median={summary['median_t_nm']:.1f}")
        axes[1].axis('off')
        fig.colorbar(im, ax=axes[1], fraction=0.046)
        fig.tight_layout()
        fig.savefig(os.path.join(out_dir, f"{stem}_thickness.png"),
                    dpi=120, bbox_inches='tight')
        plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('mrc_path')
    parser.add_argument('--lut', type=str, default=DEFAULT_LUT_PATH,
                        help=f"Path to MeasureIce HDF5 LUT. Default: bundled "
                             f"Krios_300kV.h5. Pass empty string to fall back "
                             f"to the scalar T_eff path.")
    parser.add_argument('--aperture-mrad', type=float, default=DEFAULT_APERTURE_MRAD,
                        help=f"Objective aperture half-angle in mrad (default "
                             f"{DEFAULT_APERTURE_MRAD} ~= 100 um at 300 kV). "
                             f"Closest aperture column in the LUT is used.")
    parser.add_argument('--t-eff', type=float, default=None,
                        help="Scalar T_eff in nm (only if --lut '' is passed).")
    parser.add_argument('--preset', choices=list(T_EFF_PRESETS),
                        help="Microscope preset for scalar fallback.")
    parser.add_argument('--i0-mode', choices=['percentile', 'roi', 'reference'],
                        default='percentile')
    parser.add_argument('--i0-percentile', type=float, default=99.9,
                        help="Percentile of image intensities used as I_0 "
                             "in --i0-mode percentile (default 99.9).")
    parser.add_argument('--saturation-percentile', type=float, default=99.99,
                        help="Detector hot-pixel clip; MUST be > --i0-percentile.")
    parser.add_argument('--i0-roi', type=str, default=None,
                        help="x,y,w,h of vacuum region for --i0-mode roi.")
    parser.add_argument('--i0-reference', type=str, default=None,
                        help="Path to vacuum reference MRC for --i0-mode reference.")
    parser.add_argument('--output-dir', type=str, default=None)
    parser.add_argument('--no-png', action='store_true', help="Skip PNG output")
    args = parser.parse_args()

    if not os.path.exists(args.mrc_path):
        sys.stderr.write(f"file not found: {args.mrc_path}\n")
        sys.exit(1)

    if args.saturation_percentile <= args.i0_percentile:
        sys.stderr.write(
            f"WARN: --saturation-percentile ({args.saturation_percentile}) "
            f"should be > --i0-percentile ({args.i0_percentile}); "
            f"saturation clipping will mask part of the vacuum signal.\n"
        )

    roi = None
    if args.i0_roi:
        try:
            roi = tuple(int(x) for x in args.i0_roi.split(","))
            if len(roi) != 4:
                raise ValueError
        except ValueError:
            sys.stderr.write("--i0-roi expects x,y,w,h\n")
            sys.exit(1)

    img = load_mrc(args.mrc_path)
    i0, i0_info = compute_i0(
        img, args.i0_mode,
        percentile=args.i0_percentile,
        roi=roi,
        reference_path=args.i0_reference,
    )

    use_lut = bool(args.lut) and os.path.exists(args.lut)
    if args.lut and not os.path.exists(args.lut):
        sys.stderr.write(f"WARN: LUT not found at {args.lut!r}; "
                         f"falling back to scalar T_eff.\n")
    if use_lut:
        interp, lut_info = load_lut(args.lut, args.aperture_mrad)
        t, summary = compute_thickness(
            img, i0, lut_interp=interp,
            clip_saturation_percentile=args.saturation_percentile,
        )
        summary.update(lut_info)
    else:
        t_eff = resolve_t_eff(args.t_eff, args.preset)
        t, summary = compute_thickness(
            img, i0, t_eff_nm=t_eff,
            clip_saturation_percentile=args.saturation_percentile,
        )

    summary.update(i0_info)
    summary["image"] = os.path.abspath(args.mrc_path)
    summary["image_shape"] = list(img.shape)

    save_outputs(args.mrc_path, img, t, summary,
                 output_dir=args.output_dir, write_png=not args.no_png)
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
