"""``magellon-sdk`` CLI dispatcher.

Three subcommands today, all under the ``plugin`` group:

    magellon-sdk plugin init <name>     scaffold a new plugin directory
    magellon-sdk plugin pack <dir>      validate manifest + zip into a .mpn
    magellon-sdk plugin validate <p>    validate a manifest (dir, file, or .mpn)

Hub-side commands (``hub login``, ``hub publish``, ``hub install``)
land later under the ``hub`` group when the hub itself is deployed.

Naming notes
============

- Canonical archive extension: ``.mpn`` ("Magellon plugin"). ``.zip``
  is also accepted on read paths since the underlying archive is a
  zip; ``pack`` only emits ``.mpn``.
- Canonical manifest filename inside the archive: ``manifest.yaml``.
  ``pack`` also writes a copy at the legacy name ``plugin.yaml``
  so the existing CoreService install controller (which hard-codes
  ``plugin.yaml``) keeps working until P4 lands.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

from magellon_sdk import __version__
from magellon_sdk.archive.manifest import (
    PluginArchiveManifest,
    SUPPORTED_MANIFEST_VERSIONS,
    check_sdk_compat,
    dump_manifest_yaml,
    load_manifest_bytes,
    uuid7,
)
from magellon_sdk.archive.manifest import _parse_version  # type: ignore[attr-defined]


CANONICAL_MANIFEST = "manifest.yaml"
LEGACY_MANIFEST = "plugin.yaml"
ARCHIVE_EXT = ".mpn"
LEGACY_ARCHIVE_EXTS = (".zip",)
SKIP_DIRS = {"__pycache__", ".git", ".venv", "venv", "node_modules", ".pytest_cache"}
SKIP_FILE_PATTERNS = (".pyc",)


# ---------------------------------------------------------------------------
# Manifest loading — accepts canonical OR legacy name from a source directory
# ---------------------------------------------------------------------------

def _read_source_manifest(source_dir: Path) -> tuple[PluginArchiveManifest, Path]:
    """Find and load the manifest from a plugin source directory.

    Prefers ``manifest.yaml``; falls back to ``plugin.yaml`` so v0
    plugin layouts still pack. Returns the parsed manifest and the
    path it came from."""
    canonical = source_dir / CANONICAL_MANIFEST
    legacy = source_dir / LEGACY_MANIFEST
    if canonical.exists():
        return load_manifest_bytes(canonical.read_bytes()), canonical
    if legacy.exists():
        return load_manifest_bytes(legacy.read_bytes()), legacy
    raise FileNotFoundError(
        f"{source_dir} has no {CANONICAL_MANIFEST} or {LEGACY_MANIFEST} — "
        f"did you mean `magellon-sdk plugin init`?"
    )


def _load_manifest_from_path(path: Path) -> PluginArchiveManifest:
    """Used by ``validate`` — accepts a directory, a manifest file, or
    an archive (``.mpn`` / ``.zip``)."""
    if path.is_dir():
        return _read_source_manifest(path)[0]
    if path.suffix in (ARCHIVE_EXT,) + LEGACY_ARCHIVE_EXTS:
        with zipfile.ZipFile(path) as z:
            for name in (CANONICAL_MANIFEST, LEGACY_MANIFEST):
                try:
                    with z.open(name) as f:
                        return load_manifest_bytes(f.read())
                except KeyError:
                    continue
        raise FileNotFoundError(
            f"{path} is a zip but contains neither "
            f"{CANONICAL_MANIFEST} nor {LEGACY_MANIFEST}"
        )
    if path.is_file():
        return load_manifest_bytes(path.read_bytes())
    raise FileNotFoundError(f"not found: {path}")


# ---------------------------------------------------------------------------
# init — scaffold a new plugin directory
# ---------------------------------------------------------------------------

_TEMPLATE_MANIFEST = """\
manifest_version: "{schema}"
plugin_id: {plugin_id}
# archive_id is auto-generated by `plugin pack`; leave it as-is.
archive_id: 00000000-0000-7000-8000-000000000000

name: "{name}"
version: 0.1.0
requires_sdk: ">={sdk_major}.0,<{next_major}.0"

author: "Your Name <you@example.com>"
license: MIT

category: fft     # one of: fft, ctf, motioncor, pp, ...
backend_id: {plugin_id}

requires:
  - broker
  - gpfs

resources:
  cpu_cores: 1
  memory_mb: 512
  gpu_count: 0

install:
  - method: uv
    pyproject: pyproject.toml
    requires:
      - python: ">=3.11"

health_check:
  timeout_seconds: 30
  expected_announce: true

description: One-line description of what this plugin does.
"""

_TEMPLATE_README = """\
# {name}

(Describe what the plugin does and how to use it.)

## Build + publish

1. Make sure {manifest} is filled in (`magellon-sdk plugin validate .`).
2. Pack: `magellon-sdk plugin pack .`
3. The output is `{plugin_id}-<version>{ext}`.
"""


def cmd_plugin_init(args: argparse.Namespace) -> int:
    target = Path(args.name)
    if target.exists():
        sys.stderr.write(f"error: {target} already exists\n")
        return 1
    target.mkdir(parents=True)
    plugin_id = target.name.lower().replace(" ", "-").replace("_", "-")
    sdk_major = int(__version__.split(".")[0]) if __version__[0].isdigit() else 2
    manifest_text = _TEMPLATE_MANIFEST.format(
        schema=SUPPORTED_MANIFEST_VERSIONS[-1],
        plugin_id=plugin_id,
        name=target.name,
        sdk_major=sdk_major,
        next_major=sdk_major + 1,
    )
    (target / CANONICAL_MANIFEST).write_text(manifest_text, encoding="utf-8")
    (target / "README.md").write_text(
        _TEMPLATE_README.format(
            name=target.name, plugin_id=plugin_id,
            manifest=CANONICAL_MANIFEST, ext=ARCHIVE_EXT,
        ),
        encoding="utf-8",
    )
    sys.stdout.write(f"Scaffolded {target}/ with {CANONICAL_MANIFEST} + README.md\n")
    sys.stdout.write(f"  plugin_id = {plugin_id}\n")
    sys.stdout.write(
        f"Next: edit {target}/{CANONICAL_MANIFEST}, then "
        f"`magellon-sdk plugin pack {target}`\n"
    )
    return 0


# ---------------------------------------------------------------------------
# validate — accept dir / manifest file / archive
# ---------------------------------------------------------------------------

def cmd_plugin_validate(args: argparse.Namespace) -> int:
    path = Path(args.path)
    try:
        manifest = _load_manifest_from_path(path)
    except Exception as exc:  # noqa: BLE001 — surface validation cause to operator
        sys.stderr.write(f"invalid: {exc}\n")
        return 1

    try:
        check_sdk_compat(manifest.requires_sdk, __version__)
    except Exception as exc:  # noqa: BLE001 — compat is a warning at validate time
        sys.stdout.write(
            f"OK with warning: {manifest.plugin_id} v{manifest.version} "
            f"(category={manifest.category}) — "
            f"requires_sdk {manifest.requires_sdk!r} vs CLI SDK {__version__}: {exc}\n"
        )
        return 0

    methods = ", ".join(s.method for s in manifest.install)
    sys.stdout.write(
        f"OK: {manifest.plugin_id} v{manifest.version} "
        f"(category={manifest.category}, install=[{methods}])\n"
    )
    return 0


# ---------------------------------------------------------------------------
# test — local test runner for a plugin directory (Wave 6 Phase 24)
# ---------------------------------------------------------------------------
#
# Combines the steps a plugin author should always run before pack:
#   1. Lint (manifest + install methods + DX checks).
#   2. Pytest under the plugin's tests/ directory if present.
#   3. Optional HTTP /health probe against a running instance.
#
# The intent is "one command that says yes/no" — authors don't need to
# remember to run lint + pytest separately.


def cmd_plugin_test(args: argparse.Namespace) -> int:
    import subprocess

    source = Path(args.dir).resolve()
    if not source.is_dir():
        sys.stderr.write(f"error: {source} is not a directory\n")
        return 1

    sys.stdout.write(f"=== Linting {source.name} ===\n")
    lint_rc = cmd_plugin_lint(argparse.Namespace(dir=str(source), strict=False))
    if lint_rc != 0:
        return lint_rc

    # Optional /health probe.
    if args.http:
        sys.stdout.write(f"=== Probing {args.http}/health ===\n")
        try:
            import urllib.request
            with urllib.request.urlopen(
                f"{args.http.rstrip('/')}/health", timeout=5.0,
            ) as resp:
                if 200 <= resp.status < 300:
                    sys.stdout.write(f"OK: /health → {resp.status}\n")
                else:
                    sys.stderr.write(f"error: /health → {resp.status}\n")
                    return 1
        except Exception as exc:  # noqa: BLE001
            sys.stderr.write(f"error: /health probe failed: {exc}\n")
            return 1

    # Pytest under tests/, if it exists.
    tests_dir = source / "tests"
    if tests_dir.is_dir():
        sys.stdout.write(f"=== Running pytest {tests_dir} ===\n")
        try:
            result = subprocess.run(
                [sys.executable, "-m", "pytest", str(tests_dir), "-v"],
                cwd=str(source),
            )
        except FileNotFoundError:
            sys.stderr.write("error: pytest not installed in this env\n")
            return 1
        if result.returncode != 0:
            return result.returncode
    else:
        sys.stdout.write(
            f"(no tests/ directory under {source.name} — skipping pytest)\n",
        )

    sys.stdout.write(f"\nOK: {source.name} — lint + tests passed\n")
    return 0


# ---------------------------------------------------------------------------
# scaffold — generate a runnable plugin skeleton (Wave 6 Phase 23)
# ---------------------------------------------------------------------------
#
# Unlike ``init`` (which writes manifest + README only), ``scaffold``
# generates a fully runnable plugin: FastAPI host, PluginBrokerRunner
# wired up, PluginBase subclass stub, compute stub, Dockerfile,
# pyproject.toml, tests/, .gitignore. The output is ``magellon-sdk
# plugin pack``-able immediately.
#
# Inline templates over copying an existing plugin: keeps the
# generated layout under our control as the SDK evolves; no risk of
# accidentally shipping a stale plugin's quirks.


_SCAFFOLD_MANIFEST = '''manifest_version: "1.1"

plugin_id: {plugin_id}
archive_id: 00000000-0000-7000-8000-000000000000

name: "{display_name}"
version: 0.1.0
requires_sdk: ">={sdk_major}.0,<{next_major}.0"

author: ""
license: MIT
description: >
  TODO: describe what this plugin does in one paragraph.

category: {category}
backend_id: {plugin_id}

requires:
  - broker
  - gpfs

resources:
  cpu_cores: 1
  memory_mb: 512
  gpu_count: 0
  typical_duration_seconds: 5

lifecycle:
  restart_policy: on-failure
  restart_max_retries: 5

input_schema: schemas/input.json
output_schema: schemas/output.json

install:
  - method: uv
    pyproject: pyproject.toml
    requires:
      - python: ">=3.11"
  - method: docker
    dockerfile: Dockerfile
    build_context: .
    requires:
      - docker_daemon: true

health_check:
  timeout_seconds: 30
  expected_announce: true

tags: []
'''


_SCAFFOLD_MAIN = '''"""Entry point — FastAPI host + PluginBrokerRunner daemon thread.

Run direct:  python main.py
Run packed:  magellon-sdk plugin pack . && install via CoreService.
"""
from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI

from magellon_sdk.runner import PluginBrokerRunner

from plugin.plugin import {class_name}Plugin

logger = logging.getLogger(__name__)

_plugin = {class_name}Plugin()
_runner: PluginBrokerRunner | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _runner
    # Bus + runner setup — see SDK README for the standard wiring.
    import threading

    from magellon_sdk.bus.bootstrap import install_rmq_bus
    from magellon_sdk.config import BaseAppSettings

    settings = BaseAppSettings()
    install_rmq_bus(settings.rabbitmq_settings)

    _runner = PluginBrokerRunner(plugin=_plugin, settings=settings)
    thread = threading.Thread(target=_runner.start_blocking, daemon=True)
    thread.start()

    try:
        yield
    finally:
        if _runner is not None:
            _runner.stop()


app = FastAPI(lifespan=lifespan)


@app.get("/health")
def health():
    return {{"status": "ok", "plugin": "{plugin_id}"}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host=os.environ.get("MAGELLON_PLUGIN_HOST", "0.0.0.0"),
        port=int(os.environ.get("MAGELLON_PLUGIN_PORT", "8000")),
    )
'''


_SCAFFOLD_PLUGIN_PY = '''"""Plugin contract — the SDK's PluginBase subclass.

The runner hands every incoming task to ``execute(input_data,
reporter)``. Returns the output payload; the runner wraps it in a
TaskResultMessage and publishes back.
"""
from __future__ import annotations

from typing import Any

from magellon_sdk.runner import PluginBase

from plugin.compute import run_compute


class {class_name}Plugin(PluginBase):
    """TODO: docstring."""

    plugin_id = "{plugin_id}"
    plugin_version = "0.1.0"
    category = "{category}"

    def execute(self, input_data: Any, reporter) -> dict:
        reporter.started()
        reporter.progress(10.0, "starting")
        result = run_compute(input_data)
        reporter.progress(90.0, "writing output")
        reporter.completed(output_files=[])
        return {{"result": result}}
'''


_SCAFFOLD_COMPUTE_PY = '''"""The actual algorithm — kept separate from the SDK glue so it's
unit-testable without bus / FastAPI plumbing."""
from __future__ import annotations

from typing import Any


def run_compute(input_data: Any) -> Any:
    """TODO: implement. Receives the validated input dict; returns
    whatever the output schema describes."""
    return {{"echo": input_data}}
'''


_SCAFFOLD_DOCKERFILE = '''FROM python:3.12-slim

WORKDIR /app

# System deps go here. Most pure-Python plugins need nothing extra.
# RUN apt-get update && apt-get install -y --no-install-recommends \\
#     libsomething1 \\
#  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \\
 && pip install --no-cache-dir -r requirements.txt

COPY plugin/ /app/plugin/
COPY main.py /app/main.py

ENV PYTHONPATH=/app \\
    APP_ENV=production \\
    MAGELLON_PLUGIN_HOST=0.0.0.0 \\
    MAGELLON_PLUGIN_PORT=8000

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''


_SCAFFOLD_PYPROJECT = '''[project]
name = "{plugin_id}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "magellon-sdk>={sdk_major}.0,<{next_major}.0",
    "fastapi>=0.115",
    "uvicorn>=0.30",
]

[project.optional-dependencies]
test = ["pytest>=8"]
'''


_SCAFFOLD_REQUIREMENTS = '''magellon-sdk>={sdk_major}.0,<{next_major}.0
fastapi>=0.115
uvicorn>=0.30
'''


_SCAFFOLD_GITIGNORE = '''__pycache__/
*.pyc
.venv/
.pytest_cache/
.mpn
dist/
build/
'''


_SCAFFOLD_TEST_COMPUTE = '''"""Smoke test for the compute layer. Add real cases as the algorithm
grows."""
from plugin.compute import run_compute


def test_run_compute_echoes_input():
    out = run_compute({{"x": 1}})
    assert out == {{"echo": {{"x": 1}}}}
'''


_SCAFFOLD_README = '''# {display_name}

Magellon plugin scaffolded by `magellon-sdk plugin scaffold`.

## Next steps

  1. Fill in `plugin/plugin.py` and `plugin/compute.py` with your
     algorithm.
  2. Update `manifest.yaml` (description, tags, requires_sdk).
  3. Lint: `magellon-sdk plugin lint .`
  4. Pack:  `magellon-sdk plugin pack .`
  5. Install via the Magellon admin endpoint.
'''


_SCAFFOLD_FILES = (
    ("manifest.yaml", _SCAFFOLD_MANIFEST),
    ("main.py", _SCAFFOLD_MAIN),
    ("plugin/__init__.py", ""),
    ("plugin/plugin.py", _SCAFFOLD_PLUGIN_PY),
    ("plugin/compute.py", _SCAFFOLD_COMPUTE_PY),
    ("Dockerfile", _SCAFFOLD_DOCKERFILE),
    ("pyproject.toml", _SCAFFOLD_PYPROJECT),
    ("requirements.txt", _SCAFFOLD_REQUIREMENTS),
    (".gitignore", _SCAFFOLD_GITIGNORE),
    ("tests/test_compute.py", _SCAFFOLD_TEST_COMPUTE),
    ("README.md", _SCAFFOLD_README),
)


def _class_name_from_plugin_id(plugin_id: str) -> str:
    """``ctf-plugin`` → ``CtfPlugin`` (sort of) — really
    ``CtfPluginPlugin`` because we append Plugin in the template.
    Strip a trailing ``-plugin`` to keep names sane."""
    base = plugin_id.removesuffix("-plugin").removesuffix("_plugin")
    parts = base.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p) or "Generated"


def cmd_plugin_scaffold(args: argparse.Namespace) -> int:
    target = Path(args.name).resolve()
    if target.exists() and any(target.iterdir()):
        sys.stderr.write(f"error: {target} exists and is not empty\n")
        return 1
    target.mkdir(parents=True, exist_ok=True)

    plugin_id = (
        args.plugin_id
        or target.name.lower().replace(" ", "-").replace("_", "-")
    )
    display_name = args.display_name or target.name
    category = args.category
    class_name = _class_name_from_plugin_id(plugin_id)
    sdk_major = int(__version__.split(".")[0]) if __version__[0].isdigit() else 2

    fmt_args = {
        "plugin_id": plugin_id,
        "display_name": display_name,
        "category": category,
        "class_name": class_name,
        "sdk_major": sdk_major,
        "next_major": sdk_major + 1,
    }

    for rel_path, template in _SCAFFOLD_FILES:
        out = target / rel_path
        out.parent.mkdir(parents=True, exist_ok=True)
        # The Dockerfile + gitignore have no placeholders; format() on
        # them is wasteful but cheap.
        content = template.format(**fmt_args) if "{" in template else template
        out.write_text(content, encoding="utf-8")

    sys.stdout.write(
        f"Scaffolded {target}/ ({len(_SCAFFOLD_FILES)} files).\n"
        f"  plugin_id: {plugin_id}\n"
        f"  category:  {category}\n"
        f"Next: edit plugin/compute.py and plugin/plugin.py, then "
        f"`magellon-sdk plugin lint {target}`.\n"
    )
    return 0


# ---------------------------------------------------------------------------
# lint — deeper checks than validate (Wave 6 Phase 22)
# ---------------------------------------------------------------------------

# Severity tags. Lint returns a list of (severity, message) tuples so
# the CLI can print them coherently and tests can assert on exact
# messages without parsing stdout.
LINT_ERROR = "error"
LINT_WARN = "warn"
LINT_INFO = "info"


def lint_plugin_dir(source_dir: Path) -> List[Tuple[str, str]]:  # type: ignore[name-defined]
    """Return a list of ``(severity, message)`` issues found in the
    plugin source directory.

    Issues are surfaced in three buckets:
      - ``error``: the plugin won't install or pack correctly.
        Lint returns non-zero exit if any errors are present.
      - ``warn``: probable DX papercut (stale bundled SDK wheel,
        missing health_check). Lint exits zero but the operator
        sees the message.
      - ``info``: optional polish (no tags, no homepage). Print
        only when ``--strict`` is set.

    Pure function — easy to unit test without filesystem fakery.
    """
    issues: List[Tuple[str, str]] = []

    if not source_dir.is_dir():
        issues.append((LINT_ERROR, f"{source_dir} is not a directory"))
        return issues

    # ---- 1. Manifest parses ------------------------------------------
    manifest_path = source_dir / CANONICAL_MANIFEST
    if not manifest_path.is_file():
        legacy = source_dir / LEGACY_MANIFEST
        if legacy.is_file():
            issues.append((
                LINT_WARN,
                f"{LEGACY_MANIFEST} present but no {CANONICAL_MANIFEST}; "
                f"v1 readers prefer the canonical name",
            ))
            manifest_path = legacy
        else:
            issues.append((LINT_ERROR, f"no {CANONICAL_MANIFEST} at archive root"))
            return issues

    try:
        manifest = _load_manifest_from_path(manifest_path)
    except Exception as exc:  # noqa: BLE001
        issues.append((LINT_ERROR, f"manifest schema invalid: {exc}"))
        return issues

    # ---- 2. SDK compat -----------------------------------------------
    try:
        check_sdk_compat(manifest.requires_sdk, __version__)
    except Exception as exc:  # noqa: BLE001 — warn, not error
        issues.append((
            LINT_WARN,
            f"requires_sdk {manifest.requires_sdk!r} excludes the running "
            f"SDK {__version__}: {exc}",
        ))

    # ---- 3. Install methods + their backing files --------------------
    if not manifest.install:
        issues.append((
            LINT_ERROR,
            "manifest declares no install methods (install: []) — "
            "the install pipeline has nothing to dispatch",
        ))
    for spec in manifest.install:
        if spec.method == "docker":
            if not spec.image and not spec.dockerfile:
                issues.append((
                    LINT_ERROR,
                    f"docker install spec has neither 'image' nor "
                    f"'dockerfile' set",
                ))
            elif spec.dockerfile:
                df = source_dir / spec.dockerfile
                if not df.is_file():
                    issues.append((
                        LINT_ERROR,
                        f"docker install spec references "
                        f"{spec.dockerfile!r} but that file is missing",
                    ))
        elif spec.method == "uv":
            if not spec.pyproject:
                issues.append((
                    LINT_ERROR,
                    "uv install spec is missing 'pyproject:'",
                ))
            else:
                pp = source_dir / spec.pyproject
                if not pp.is_file():
                    issues.append((
                        LINT_ERROR,
                        f"uv install spec references {spec.pyproject!r} "
                        f"but that file is missing",
                    ))

    # ---- 4. Bundled SDK wheel staleness (common DX trap) -------------
    wheels_dir = source_dir / "wheels"
    if wheels_dir.is_dir():
        wheels = sorted(wheels_dir.glob("magellon_sdk-*.whl"))
        if not wheels:
            issues.append((
                LINT_INFO,
                "wheels/ directory present but no magellon_sdk-*.whl found",
            ))
        else:
            # Parse the wheel's version from its filename; warn if
            # it's older than the SDK version this CLI is running as.
            latest = wheels[-1].name
            # Convention: magellon_sdk-<version>-py3-none-any.whl
            parts = latest.split("-")
            wheel_version = parts[1] if len(parts) > 1 else ""
            try:
                wv = _parse_version(wheel_version)
                cv = _parse_version(__version__)
                if wv < cv:
                    issues.append((
                        LINT_WARN,
                        f"bundled SDK wheel {wheel_version} is older than "
                        f"the CLI's SDK {__version__} — rebuild before "
                        f"packing or the install may break with "
                        f"ImportError (memory: project_plugin_sdk_wheel_drift)",
                    ))
            except (ValueError, TypeError):
                pass

    # ---- 5. Health check sanity --------------------------------------
    hc = manifest.health_check
    if hc.timeout_seconds < 5:
        issues.append((
            LINT_WARN,
            f"health_check.timeout_seconds={hc.timeout_seconds} is very low; "
            f"cold-start plugins may fail the install gate",
        ))
    if hc.timeout_seconds > 300:
        issues.append((
            LINT_WARN,
            f"health_check.timeout_seconds={hc.timeout_seconds} is very high; "
            f"operator install requests will block on a hung plugin",
        ))

    # ---- 6. Polish: tags / description / homepage --------------------
    if not manifest.tags:
        issues.append((LINT_INFO, "no tags declared — search/discovery suffers"))
    if not manifest.description:
        issues.append((LINT_INFO, "no description set"))
    if not manifest.author:
        issues.append((LINT_INFO, "no author set"))

    # ---- 7. Replicas/lifecycle sanity (manifest v1.1) ----------------
    replicas = manifest.resources.replicas
    if replicas is not None:
        if replicas.desired > replicas.max:
            issues.append((
                LINT_ERROR,
                f"replicas.desired={replicas.desired} > max={replicas.max}",
            ))

    return issues


def cmd_plugin_lint(args: argparse.Namespace) -> int:
    source = Path(args.dir).resolve()
    issues = lint_plugin_dir(source)

    strict = bool(getattr(args, "strict", False))
    errors = [m for sev, m in issues if sev == LINT_ERROR]
    warns = [m for sev, m in issues if sev == LINT_WARN]
    infos = [m for sev, m in issues if sev == LINT_INFO]

    for m in errors:
        sys.stderr.write(f"error: {m}\n")
    for m in warns:
        sys.stderr.write(f"warn: {m}\n")
    if strict:
        for m in infos:
            sys.stderr.write(f"info: {m}\n")

    if errors:
        return 1
    if strict and warns:
        return 1
    sys.stdout.write(
        f"OK: {source.name} — {len(errors)} errors, {len(warns)} warnings"
        f"{', ' + str(len(infos)) + ' info' if strict else ''}\n",
    )
    return 0


# ---------------------------------------------------------------------------
# pack — the meat of P2
# ---------------------------------------------------------------------------

def _iter_pack_files(source_dir: Path) -> Iterable[Path]:
    """Walk the source directory yielding files to include in the
    archive. Skips hidden dirs/files, build artifacts, and the
    source manifest itself (we write a regenerated one)."""
    for root, dirs, files in os.walk(source_dir):
        # In-place mutation of dirs[] tells os.walk what NOT to descend into.
        dirs[:] = [
            d for d in dirs
            if not d.startswith(".") and d not in SKIP_DIRS
        ]
        for name in files:
            if name.startswith("."):
                continue
            if name.endswith(SKIP_FILE_PATTERNS):
                continue
            # Skip the source manifest — pack writes a regenerated
            # version with stamped checksums + archive_id.
            if name in (CANONICAL_MANIFEST, LEGACY_MANIFEST):
                continue
            yield Path(root) / name


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _warn_external_uv_sources(src: Path) -> None:
    """Warn if pyproject.toml's ``[tool.uv.sources]`` references paths
    that resolve outside the source directory.

    Such paths (e.g. ``path = "../../magellon-sdk"``) are common in
    workspace dev setups but break at install time because the
    archive is extracted into a different location. The bundled-wheel
    pattern (``path = "wheels/foo.whl"``) is the cross-host fix.

    Read-only via stdlib ``tomllib`` (Python 3.11+); on older Pythons
    or on parse errors we silently skip — the lint is a hint, not a
    gate.
    """
    pyproject = src / "pyproject.toml"
    if not pyproject.exists():
        return
    try:
        import tomllib  # type: ignore[import-not-found]
    except ImportError:
        return
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return
    sources = (
        data.get("tool", {}).get("uv", {}).get("sources", {})
    )
    if not isinstance(sources, dict):
        return
    bad: list[str] = []
    for name, spec in sources.items():
        if not isinstance(spec, dict):
            continue
        path_value = spec.get("path")
        if not path_value:
            continue
        # Resolve relative to the plugin source dir.
        resolved = (src / path_value).resolve()
        try:
            resolved.relative_to(src.resolve())
        except ValueError:
            bad.append(f"  {name} -> {path_value}  (resolves to {resolved})")
    if bad:
        sys.stdout.write(
            "warning: pyproject.toml has [tool.uv.sources] entries that "
            "resolve outside the plugin dir:\n"
            + "\n".join(bad) + "\n"
            + "  These paths will not exist after archive extraction. "
            "Bundle a wheel under wheels/ or pin via PyPI version "
            "instead.\n"
        )


def _stamp_manifest(
    manifest: PluginArchiveManifest, file_checksums: dict[str, str],
) -> PluginArchiveManifest:
    """Update the manifest with packed-archive metadata.

    - ``archive_id``: regenerate to a fresh UUID v7. The pack tool
      represents one *build*; subsequent rebuilds get new ids.
    - ``updated``: stamp now in UTC. ``created`` is preserved if
      already meaningful, otherwise also set to now.
    - ``file_checksums``: replace with the freshly computed map.
    """
    now = datetime.now(timezone.utc)
    payload = manifest.model_dump(mode="python")
    payload["archive_id"] = str(uuid7())
    payload["updated"] = now
    if not payload.get("created") or payload["created"] == manifest.updated:
        payload["created"] = now
    payload["file_checksums"] = file_checksums
    return PluginArchiveManifest.model_validate(payload)


def cmd_plugin_pack(args: argparse.Namespace) -> int:
    src = Path(args.dir).resolve()
    if not src.is_dir():
        sys.stderr.write(f"error: {src} is not a directory\n")
        return 1

    try:
        manifest, _src_path = _read_source_manifest(src)
    except Exception as exc:  # noqa: BLE001
        sys.stderr.write(f"error: {exc}\n")
        return 1

    # Lint pyproject.toml for [tool.uv.sources] paths that escape the
    # plugin dir. Such paths are common in dev (e.g. SDK at
    # ``../../magellon-sdk``) but break at install time because the
    # archive is unpacked into a different location. Warn loudly so
    # the author either bundles a wheel under ``wheels/`` or uses a
    # PyPI-style version pin.
    _warn_external_uv_sources(src)

    # Collect files to pack + their checksums. Paths in the archive
    # are POSIX-relative to the package root (which itself is the
    # source directory's name) — this is what the install controller
    # extracts back out.
    pack_files: list[tuple[Path, str]] = []
    file_checksums: dict[str, str] = {}
    for full in _iter_pack_files(src):
        arcname = full.relative_to(src).as_posix()
        digest = _sha256(full)
        pack_files.append((full, arcname))
        file_checksums[arcname] = digest

    # Stamp manifest with archive_id + updated + checksums.
    final_manifest = _stamp_manifest(manifest, file_checksums)
    manifest_yaml = dump_manifest_yaml(final_manifest)

    # Output path defaults to <plugin_id>-<version>.mpn next to source.
    out = Path(
        args.output
        or src.parent / f"{final_manifest.plugin_id}-{final_manifest.version}{ARCHIVE_EXT}"
    )
    if out.exists() and not args.force:
        sys.stderr.write(f"error: {out} already exists (pass --force to overwrite)\n")
        return 1

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        # Canonical manifest at the archive root.
        z.writestr(CANONICAL_MANIFEST, manifest_yaml)
        # Legacy alias — same content, alternate filename. Lets the
        # existing CoreService install controller (hard-coded to
        # plugin.yaml) read v1 archives until P4 retires it.
        z.writestr(LEGACY_MANIFEST, manifest_yaml)
        for full, arcname in pack_files:
            z.write(full, arcname=arcname)

    archive_size = out.stat().st_size
    archive_sha = _sha256(out)
    sys.stdout.write(
        f"Packed {final_manifest.plugin_id} v{final_manifest.version}\n"
        f"  archive: {out}\n"
        f"  size:    {archive_size:,} bytes\n"
        f"  sha256:  {archive_sha}\n"
        f"  files:   {len(pack_files)} (+ 2 manifest aliases)\n"
    )
    return 0


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="magellon-sdk",
        description="Magellon Plugin SDK — author tooling for .mpn archives.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"magellon-sdk {__version__}",
    )

    sub = parser.add_subparsers(dest="group", required=False, metavar="GROUP")

    # plugin group
    plugin = sub.add_parser("plugin", help="Plugin archive author tooling.")
    plugin_sub = plugin.add_subparsers(
        dest="command", required=True, metavar="COMMAND",
    )

    p_init = plugin_sub.add_parser(
        "init", help="Scaffold a new plugin archive directory.",
    )
    p_init.add_argument("name", help="Directory to create for the new plugin.")
    p_init.set_defaults(func=cmd_plugin_init)

    p_pack = plugin_sub.add_parser(
        "pack",
        help=f"Validate {CANONICAL_MANIFEST} and zip the directory to {ARCHIVE_EXT}.",
    )
    p_pack.add_argument("dir", help="Plugin directory containing manifest.yaml.")
    p_pack.add_argument(
        "-o", "--output",
        help=f"Output archive path. Defaults to "
             f"<plugin_id>-<version>{ARCHIVE_EXT} alongside the source dir.",
    )
    p_pack.add_argument(
        "--force", action="store_true",
        help="Overwrite an existing output archive.",
    )
    p_pack.set_defaults(func=cmd_plugin_pack)

    p_val = plugin_sub.add_parser(
        "validate",
        help=f"Validate a plugin manifest (dir / {CANONICAL_MANIFEST} / {ARCHIVE_EXT}).",
    )
    p_val.add_argument("path")
    p_val.set_defaults(func=cmd_plugin_validate)

    p_lint = plugin_sub.add_parser(
        "lint",
        help="Deeper checks than validate — install method completeness, "
             "bundled wheel staleness, health-check sanity, polish hints.",
    )
    p_lint.add_argument("dir", help="Plugin directory.")
    p_lint.add_argument(
        "--strict", action="store_true",
        help="Treat warnings + infos as failures (CI gate flag).",
    )
    p_lint.set_defaults(func=cmd_plugin_lint)

    p_scaffold = plugin_sub.add_parser(
        "scaffold",
        help="Generate a runnable plugin skeleton (manifest, main.py, "
             "plugin/, Dockerfile, pyproject, tests).",
    )
    p_scaffold.add_argument("name", help="Directory to create.")
    p_scaffold.add_argument(
        "--category", required=True,
        help="TaskCategory the plugin serves (e.g. 'fft', 'ctf').",
    )
    p_scaffold.add_argument(
        "--plugin-id",
        help="Explicit plugin_id; defaults to the directory name lowercased.",
    )
    p_scaffold.add_argument(
        "--display-name",
        help="Human-readable name for manifest; defaults to the directory name.",
    )
    p_scaffold.set_defaults(func=cmd_plugin_scaffold)

    p_test = plugin_sub.add_parser(
        "test",
        help="Run the author's pre-pack checks: lint + pytest "
             "+ optional /health probe.",
    )
    p_test.add_argument("dir", help="Plugin directory.")
    p_test.add_argument(
        "--http",
        help="Probe this URL's /health before running pytest "
             "(e.g. http://127.0.0.1:8000). Optional.",
    )
    p_test.set_defaults(func=cmd_plugin_test)

    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        # Bare ``magellon-sdk`` with no subcommand — print help, exit 0.
        parser.print_help()
        return 0
    return args.func(args)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
