"""``magellon-sdk`` CLI dispatcher.

Three subcommands today, all under the ``plugin`` group:

    magellon-sdk plugin init <name>     scaffold a new plugin directory
    magellon-sdk plugin pack <dir>      validate manifest + zip into a .mpn
    magellon-sdk plugin validate <p>    validate a manifest (dir, file, or .mpn)

Hub-side commands (``hub login``, ``hub publish``, ``hub install``)
land later under the ``hub`` group when the hub itself is deployed.

Naming notes
============

- Canonical archive extension: ``.mpn`` ("Magellon plugin"). ``.zip``
  is also accepted on read paths since the underlying archive is a
  zip; ``pack`` only emits ``.mpn``.
- Canonical manifest filename inside the archive: ``manifest.yaml``.
  ``pack`` also writes a copy at the legacy name ``plugin.yaml``
  so the existing CoreService install controller (which hard-codes
  ``plugin.yaml``) keeps working until P4 lands.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Optional

from magellon_sdk import __version__
from magellon_sdk.archive.manifest import (
    PluginArchiveManifest,
    SUPPORTED_MANIFEST_VERSIONS,
    check_sdk_compat,
    dump_manifest_yaml,
    load_manifest_bytes,
    uuid7,
)


CANONICAL_MANIFEST = "manifest.yaml"
LEGACY_MANIFEST = "plugin.yaml"
ARCHIVE_EXT = ".mpn"
LEGACY_ARCHIVE_EXTS = (".zip",)
SKIP_DIRS = {"__pycache__", ".git", ".venv", "venv", "node_modules", ".pytest_cache"}
SKIP_FILE_PATTERNS = (".pyc",)


# ---------------------------------------------------------------------------
# Manifest loading — accepts canonical OR legacy name from a source directory
# ---------------------------------------------------------------------------

def _read_source_manifest(source_dir: Path) -> tuple[PluginArchiveManifest, Path]:
    """Find and load the manifest from a plugin source directory.

    Prefers ``manifest.yaml``; falls back to ``plugin.yaml`` so v0
    plugin layouts still pack. Returns the parsed manifest and the
    path it came from."""
    canonical = source_dir / CANONICAL_MANIFEST
    legacy = source_dir / LEGACY_MANIFEST
    if canonical.exists():
        return load_manifest_bytes(canonical.read_bytes()), canonical
    if legacy.exists():
        return load_manifest_bytes(legacy.read_bytes()), legacy
    raise FileNotFoundError(
        f"{source_dir} has no {CANONICAL_MANIFEST} or {LEGACY_MANIFEST} — "
        f"did you mean `magellon-sdk plugin init`?"
    )


def _load_manifest_from_path(path: Path) -> PluginArchiveManifest:
    """Used by ``validate`` — accepts a directory, a manifest file, or
    an archive (``.mpn`` / ``.zip``)."""
    if path.is_dir():
        return _read_source_manifest(path)[0]
    if path.suffix in (ARCHIVE_EXT,) + LEGACY_ARCHIVE_EXTS:
        with zipfile.ZipFile(path) as z:
            for name in (CANONICAL_MANIFEST, LEGACY_MANIFEST):
                try:
                    with z.open(name) as f:
                        return load_manifest_bytes(f.read())
                except KeyError:
                    continue
        raise FileNotFoundError(
            f"{path} is a zip but contains neither "
            f"{CANONICAL_MANIFEST} nor {LEGACY_MANIFEST}"
        )
    if path.is_file():
        return load_manifest_bytes(path.read_bytes())
    raise FileNotFoundError(f"not found: {path}")


# ---------------------------------------------------------------------------
# init — scaffold a new plugin directory
# ---------------------------------------------------------------------------

_TEMPLATE_MANIFEST = """\
manifest_version: "{schema}"
plugin_id: {plugin_id}
# archive_id is auto-generated by `plugin pack`; leave it as-is.
archive_id: 00000000-0000-7000-8000-000000000000

name: "{name}"
version: 0.1.0
requires_sdk: ">={sdk_major}.0,<{next_major}.0"

author: "Your Name <you@example.com>"
license: MIT

category: fft     # one of: fft, ctf, motioncor, pp, ...
backend_id: {plugin_id}

requires:
  - broker
  - gpfs

resources:
  cpu_cores: 1
  memory_mb: 512
  gpu_count: 0

install:
  - method: uv
    pyproject: pyproject.toml
    requires:
      - python: ">=3.11"

health_check:
  timeout_seconds: 30
  expected_announce: true

description: One-line description of what this plugin does.
"""

_TEMPLATE_README = """\
# {name}

(Describe what the plugin does and how to use it.)

## Build + publish

1. Make sure {manifest} is filled in (`magellon-sdk plugin validate .`).
2. Pack: `magellon-sdk plugin pack .`
3. The output is `{plugin_id}-<version>{ext}`.
"""


def cmd_plugin_init(args: argparse.Namespace) -> int:
    target = Path(args.name)
    if target.exists():
        sys.stderr.write(f"error: {target} already exists\n")
        return 1
    target.mkdir(parents=True)
    plugin_id = target.name.lower().replace(" ", "-").replace("_", "-")
    sdk_major = int(__version__.split(".")[0]) if __version__[0].isdigit() else 2
    manifest_text = _TEMPLATE_MANIFEST.format(
        schema=SUPPORTED_MANIFEST_VERSIONS[-1],
        plugin_id=plugin_id,
        name=target.name,
        sdk_major=sdk_major,
        next_major=sdk_major + 1,
    )
    (target / CANONICAL_MANIFEST).write_text(manifest_text, encoding="utf-8")
    (target / "README.md").write_text(
        _TEMPLATE_README.format(
            name=target.name, plugin_id=plugin_id,
            manifest=CANONICAL_MANIFEST, ext=ARCHIVE_EXT,
        ),
        encoding="utf-8",
    )
    sys.stdout.write(f"Scaffolded {target}/ with {CANONICAL_MANIFEST} + README.md\n")
    sys.stdout.write(f"  plugin_id = {plugin_id}\n")
    sys.stdout.write(
        f"Next: edit {target}/{CANONICAL_MANIFEST}, then "
        f"`magellon-sdk plugin pack {target}`\n"
    )
    return 0


# ---------------------------------------------------------------------------
# validate — accept dir / manifest file / archive
# ---------------------------------------------------------------------------

def cmd_plugin_validate(args: argparse.Namespace) -> int:
    path = Path(args.path)
    try:
        manifest = _load_manifest_from_path(path)
    except Exception as exc:  # noqa: BLE001 — surface validation cause to operator
        sys.stderr.write(f"invalid: {exc}\n")
        return 1

    try:
        check_sdk_compat(manifest.requires_sdk, __version__)
    except Exception as exc:  # noqa: BLE001 — compat is a warning at validate time
        sys.stdout.write(
            f"OK with warning: {manifest.plugin_id} v{manifest.version} "
            f"(category={manifest.category}) — "
            f"requires_sdk {manifest.requires_sdk!r} vs CLI SDK {__version__}: {exc}\n"
        )
        return 0

    methods = ", ".join(s.method for s in manifest.install)
    sys.stdout.write(
        f"OK: {manifest.plugin_id} v{manifest.version} "
        f"(category={manifest.category}, install=[{methods}])\n"
    )
    return 0


# ---------------------------------------------------------------------------
# pack — the meat of P2
# ---------------------------------------------------------------------------

def _iter_pack_files(source_dir: Path) -> Iterable[Path]:
    """Walk the source directory yielding files to include in the
    archive. Skips hidden dirs/files, build artifacts, and the
    source manifest itself (we write a regenerated one)."""
    for root, dirs, files in os.walk(source_dir):
        # In-place mutation of dirs[] tells os.walk what NOT to descend into.
        dirs[:] = [
            d for d in dirs
            if not d.startswith(".") and d not in SKIP_DIRS
        ]
        for name in files:
            if name.startswith("."):
                continue
            if name.endswith(SKIP_FILE_PATTERNS):
                continue
            # Skip the source manifest — pack writes a regenerated
            # version with stamped checksums + archive_id.
            if name in (CANONICAL_MANIFEST, LEGACY_MANIFEST):
                continue
            yield Path(root) / name


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _warn_external_uv_sources(src: Path) -> None:
    """Warn if pyproject.toml's ``[tool.uv.sources]`` references paths
    that resolve outside the source directory.

    Such paths (e.g. ``path = "../../magellon-sdk"``) are common in
    workspace dev setups but break at install time because the
    archive is extracted into a different location. The bundled-wheel
    pattern (``path = "wheels/foo.whl"``) is the cross-host fix.

    Read-only via stdlib ``tomllib`` (Python 3.11+); on older Pythons
    or on parse errors we silently skip — the lint is a hint, not a
    gate.
    """
    pyproject = src / "pyproject.toml"
    if not pyproject.exists():
        return
    try:
        import tomllib  # type: ignore[import-not-found]
    except ImportError:
        return
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return
    sources = (
        data.get("tool", {}).get("uv", {}).get("sources", {})
    )
    if not isinstance(sources, dict):
        return
    bad: list[str] = []
    for name, spec in sources.items():
        if not isinstance(spec, dict):
            continue
        path_value = spec.get("path")
        if not path_value:
            continue
        # Resolve relative to the plugin source dir.
        resolved = (src / path_value).resolve()
        try:
            resolved.relative_to(src.resolve())
        except ValueError:
            bad.append(f"  {name} -> {path_value}  (resolves to {resolved})")
    if bad:
        sys.stdout.write(
            "warning: pyproject.toml has [tool.uv.sources] entries that "
            "resolve outside the plugin dir:\n"
            + "\n".join(bad) + "\n"
            + "  These paths will not exist after archive extraction. "
            "Bundle a wheel under wheels/ or pin via PyPI version "
            "instead.\n"
        )


def _stamp_manifest(
    manifest: PluginArchiveManifest, file_checksums: dict[str, str],
) -> PluginArchiveManifest:
    """Update the manifest with packed-archive metadata.

    - ``archive_id``: regenerate to a fresh UUID v7. The pack tool
      represents one *build*; subsequent rebuilds get new ids.
    - ``updated``: stamp now in UTC. ``created`` is preserved if
      already meaningful, otherwise also set to now.
    - ``file_checksums``: replace with the freshly computed map.
    """
    now = datetime.now(timezone.utc)
    payload = manifest.model_dump(mode="python")
    payload["archive_id"] = str(uuid7())
    payload["updated"] = now
    if not payload.get("created") or payload["created"] == manifest.updated:
        payload["created"] = now
    payload["file_checksums"] = file_checksums
    return PluginArchiveManifest.model_validate(payload)


def cmd_plugin_pack(args: argparse.Namespace) -> int:
    src = Path(args.dir).resolve()
    if not src.is_dir():
        sys.stderr.write(f"error: {src} is not a directory\n")
        return 1

    try:
        manifest, _src_path = _read_source_manifest(src)
    except Exception as exc:  # noqa: BLE001
        sys.stderr.write(f"error: {exc}\n")
        return 1

    # Lint pyproject.toml for [tool.uv.sources] paths that escape the
    # plugin dir. Such paths are common in dev (e.g. SDK at
    # ``../../magellon-sdk``) but break at install time because the
    # archive is unpacked into a different location. Warn loudly so
    # the author either bundles a wheel under ``wheels/`` or uses a
    # PyPI-style version pin.
    _warn_external_uv_sources(src)

    # Collect files to pack + their checksums. Paths in the archive
    # are POSIX-relative to the package root (which itself is the
    # source directory's name) — this is what the install controller
    # extracts back out.
    pack_files: list[tuple[Path, str]] = []
    file_checksums: dict[str, str] = {}
    for full in _iter_pack_files(src):
        arcname = full.relative_to(src).as_posix()
        digest = _sha256(full)
        pack_files.append((full, arcname))
        file_checksums[arcname] = digest

    # Stamp manifest with archive_id + updated + checksums.
    final_manifest = _stamp_manifest(manifest, file_checksums)
    manifest_yaml = dump_manifest_yaml(final_manifest)

    # Output path defaults to <plugin_id>-<version>.mpn next to source.
    out = Path(
        args.output
        or src.parent / f"{final_manifest.plugin_id}-{final_manifest.version}{ARCHIVE_EXT}"
    )
    if out.exists() and not args.force:
        sys.stderr.write(f"error: {out} already exists (pass --force to overwrite)\n")
        return 1

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        # Canonical manifest at the archive root.
        z.writestr(CANONICAL_MANIFEST, manifest_yaml)
        # Legacy alias — same content, alternate filename. Lets the
        # existing CoreService install controller (hard-coded to
        # plugin.yaml) read v1 archives until P4 retires it.
        z.writestr(LEGACY_MANIFEST, manifest_yaml)
        for full, arcname in pack_files:
            z.write(full, arcname=arcname)

    archive_size = out.stat().st_size
    archive_sha = _sha256(out)
    sys.stdout.write(
        f"Packed {final_manifest.plugin_id} v{final_manifest.version}\n"
        f"  archive: {out}\n"
        f"  size:    {archive_size:,} bytes\n"
        f"  sha256:  {archive_sha}\n"
        f"  files:   {len(pack_files)} (+ 2 manifest aliases)\n"
    )
    return 0


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="magellon-sdk",
        description="Magellon Plugin SDK — author tooling for .mpn archives.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"magellon-sdk {__version__}",
    )

    sub = parser.add_subparsers(dest="group", required=False, metavar="GROUP")

    # plugin group
    plugin = sub.add_parser("plugin", help="Plugin archive author tooling.")
    plugin_sub = plugin.add_subparsers(
        dest="command", required=True, metavar="COMMAND",
    )

    p_init = plugin_sub.add_parser(
        "init", help="Scaffold a new plugin archive directory.",
    )
    p_init.add_argument("name", help="Directory to create for the new plugin.")
    p_init.set_defaults(func=cmd_plugin_init)

    p_pack = plugin_sub.add_parser(
        "pack",
        help=f"Validate {CANONICAL_MANIFEST} and zip the directory to {ARCHIVE_EXT}.",
    )
    p_pack.add_argument("dir", help="Plugin directory containing manifest.yaml.")
    p_pack.add_argument(
        "-o", "--output",
        help=f"Output archive path. Defaults to "
             f"<plugin_id>-<version>{ARCHIVE_EXT} alongside the source dir.",
    )
    p_pack.add_argument(
        "--force", action="store_true",
        help="Overwrite an existing output archive.",
    )
    p_pack.set_defaults(func=cmd_plugin_pack)

    p_val = plugin_sub.add_parser(
        "validate",
        help=f"Validate a plugin manifest (dir / {CANONICAL_MANIFEST} / {ARCHIVE_EXT}).",
    )
    p_val.add_argument("path")
    p_val.set_defaults(func=cmd_plugin_validate)

    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        # Bare ``magellon-sdk`` with no subcommand — print help, exit 0.
        parser.print_help()
        return 0
    return args.func(args)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
