version: '3.8'

services:
  backend:
    build:
      context: ./2dclassifierbackend
      dockerfile: Dockerfile
    volumes:
      - ../2dclass_evaluator:/app/2dclass_evaluator
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./2dclassifierFrontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${BACKEND_URL} 
    ports:
      - "3000:80" 
