"""Compatibility shim — re-exports canonical DTOs from the SDK."""
from magellon_sdk.models import (  # noqa: F401
    COMPLETED,
    CheckRequirementsResult,
    CryoEmImageTaskData,
    DebugInfo,
    FAILED,
    FFT_TASK,
    FftTask,
    FftTaskData,
    IN_PROGRESS,
    ImageMetaData,
    JobDto,
    OutputFile,
    PENDING,
    PluginInfo,
    PluginInfoSingleton,
    RecuirementResultEnum,
    RequirementResult,
    TaskBase,
    TaskCategory,
    TaskDto,
    TaskOutcome,
    TaskResultDto,
    TaskStatus,
    TaskStatusEnum,
)
